id: PD0CED0FF
initial_creation_type: ocr
source_metadata:
  volumes:
    2606582904af4a7d86dd2c2320f48a25:
      base_file: v065.txt
      image_group_id: I1PD95910
      title: ཆོས་རྗེས་སུ་དྲན་པའི་འགྲེལ་པ།
      total_pages: 1498
      volume_number: 65
